### ISSUE TITLE
suggestions to improve functionality

### ISSUE THREAD

**Issue by yysun8** [shreyashankar/planner#5]
hi! 
 
some suggestions: 

1) maybe add option for user to indicate priority levels: low, medium, high i.e. if I want to have this assignment done asap then planner will schedule more sessions to finish as close as possible to right now; if low priority then new assignments can push the low priority assignment back and have the sessions more spread out

2) allow user to indicate when they want to start this assignment -- for example if I wanted to begin two days from now

3) break time being in hours might be more efficient

**Comment by shreyashankar** [comment]
2 and 3 done. 1 is what i will work on today :) 👍
